# Generated by Django 2.2.12 on 2020-05-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='id_tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Tipo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='id_tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Tipo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='image',
            field=models.FileField(default='images/noimg.jpg', upload_to='images/'),
        ),
    ]
