# Generated by Django 2.2.12 on 2020-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200525_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.FileField(default='blog/static/images/noimg.jpg', upload_to='blog/static/images/'),
        ),
    ]
