# Generated by Django 2.2.12 on 2020-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200525_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.FileField(default='static/images/receitas/noimg.jpg', upload_to='static/images/receitas/'),
        ),
    ]
