# Generated by Django 2.2.12 on 2020-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200525_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.FileField(default='blog/static/images/receitas/noimg.jpg', upload_to='blog/static/images/receitas/'),
        ),
    ]
