# Generated by Django 2.2.12 on 2020-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200525_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='short_desc',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
