# Generated by Django 3.2.5 on 2023-08-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_receita_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(default='receitas/noimg.jpg', upload_to='receitas/'),
        ),
    ]
